- name: "Setup Nucypher"
  hosts: "{{ play_hosts }}"
  remote_user: "{{default_user}}"
  gather_facts: no
  tasks:

    - name: Recursively change ownership of geth directory
      become: yes
      file:
        path: /home/nucypher/geth
        state: directory
        recurse: yes
        owner: nucypher

    - name: "pull {{ nucypher_image | default('nucypher/nucypher:latest') }}"
      become: yes
      docker_image:
        name: nucypher/nucypher
        source: pull

    - name: "check if /home/nucypher/nucypher/ursula.json exists"
      become: yes
      become_user: nucypher
      stat:
        path: /home/nucypher/nucypher/ursula.json
      register: ursula_check

    - name: Find my public ip
      when: ursula_check.stat.exists == False
      uri:
        url: http://ifconfig.me/ip
        return_content: yes
      register: ip_response

    - name: "init Ursula worker"
      become: yes
      become_user: nucypher
      when: ursula_check.stat.exists == False
      command: "docker run -v /home/nucypher:/root/.local/share/ -e NUCYPHER_KEYRING_PASSWORD -it {{ nucypher_image | default('nucypher/nucypher:latest') }}  nucypher ursula init --provider /root/.local/share/geth/.ethereum/goerli/geth.ipc --poa --worker-address {{active_account.stdout}} --rest-host {{ip_response.content}} --network {{network_name}} {{nucypher_ursula_init_options | default('')}}"
      environment:
        NUCYPHER_KEYRING_PASSWORD: "{{NUCYPHER_KEYRING_PASSWORD}}"
