- name: "Update Running Ursula"
  hosts: "{{ play_hosts }}"
  remote_user: "{{default_user}}"
  gather_facts: no
  tasks:

    - name: "pull {{ nucypher_image | default('nucypher/nucypher:latest') }}"
      become: yes
      docker_image:
        name: "{{ nucypher_image | default('nucypher/nucypher:latest') }}"
        source: pull
        force_source: yes

    - name: Stop Ursula
      become: yes
      become_user: nucypher
      docker_container:
        name: ursula
        state: stopped

    - set_fact: restarting_geth=True
    - name: Stop Geth
      become: yes
      docker_container:
        name: geth
        state: stopped

- import_playbook: run_geth.yml
- import_playbook: run_ursula.yml